modLoader = "javafml"
loaderVersion = "[48,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "xaeroplus"
version = "1.20.2"
displayName = "XaeroPlus"
authors = "rfresh2"
description = '''
Xaero WorldMap / Minimap Extra Features
'''
logoFile = "icon.jpg"
displayTest="IGNORE_ALL_VERSION"

[[dependencies.xaeroplus]]
modId = "forge"
mandatory = true
versionRange = "[48,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.xaeroplus]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.xaeroplus]]
modId = "xaerominimap"
mandatory = false
versionRange = "[23.8.3]"
ordering = "BEFORE"
side = "CLIENT"

[[dependencies.xaeroplus]]
modId = "xaerobetterpvp"
mandatory = false
versionRange = "[23.8.3]"
ordering = "BEFORE"
side = "CLIENT"

[[dependencies.xaeroplus]]
modId = "xaeroworldmap"
mandatory = true
versionRange = "[1.35.0]"
ordering = "BEFORE"
side = "CLIENT"
