name: 1.19.4 Build

on:
  pull_request:
  push:
    branches:
      - "1.19.4"

env:
  MINECRAFT_VERSION: "1.19.4"
  MINECRAFT_VERSION_SHORT: "1.19.4"
  FABRIC_API_VERSION: "0.87.2+1.19.4"
  FABRIC_API_MODRINTH_VERSION_ID: "nyAmoHlr"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Gradle Wrapper Verification
      uses: gradle/wrapper-validation-action@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Elevate wrapper permissions
      run: chmod +x ./gradlew

    - name: Build Mods
      uses: gradle/gradle-build-action@v3
      with:
        arguments: build

    - name: Get WorldMap Version
      run: |
        echo "WORLDMAP_VERSION=$(./gradlew -q printWorldMapVersion)" >> $GITHUB_ENV

    - name: Get Minimap Version
      run: |
        echo "MINIMAP_VERSION=$(./gradlew -q printMinimapVersion)" >> $GITHUB_ENV

    - name: Get XaeroPlus Version
      run: |
        echo "XP_VERSION=$(./gradlew -q printXaeroPlusVersion)" >> $GITHUB_ENV

    - name: Get Fabric Jar Filename
      run: |
        echo "XP_FABRIC=XaeroPlus-${{ env.XP_VERSION}}+fabric-${{ env.MINECRAFT_VERSION }}-WM${{ env.WORLDMAP_VERSION }}-MM${{ env.MINIMAP_VERSION }}" >> $GITHUB_ENV

    - name: Get Forge Jar Filename
      run: |
        echo "XP_FORGE=XaeroPlus-${{ env.XP_VERSION}}+forge-${{ env.MINECRAFT_VERSION }}-WM${{ env.WORLDMAP_VERSION }}-MM${{ env.MINIMAP_VERSION }}" >> $GITHUB_ENV

    - name: Upload Fabric Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.XP_FABRIC }}
        path: fabric/build/libs/${{ env.XP_FABRIC }}.jar
        if-no-files-found: error

    - name: Upload Forge Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.XP_FORGE }}
        path: forge/build/libs/${{ env.XP_FORGE }}.jar
        if-no-files-found: error
